### ISSUE TITLE
Homebrew installation error on Linus

### ISSUE THREAD

**Issue by taorepoara** [slidesk/slidesk#171]
Got an error while trying to install Slidesk with Homebrew on linux.

Here are the installation logs:

```bash
$ brew tap gouz/tools
==> Tapping gouz/tools
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/gouz/homebrew-tools'...
remote: Enumerating objects: 386, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 386 (delta 53), reused 60 (delta 26), pack-reused 299 (from 1)
Receiving objects: 100% (386/386), 45.86 KiB | 1.83 MiB/s, done.
Resolving deltas: 100% (154/154), done.
Tapped 2 formulae (14 files, 120.4KB).
$ brew install slidesk
Error: gouz/tools/slidesk: formula requires at least a URL
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:322:in `determine_active_spec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:256:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:568:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:777:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:980:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:328:in `block in load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api.rb:203:in `with_no_api_env_if_needed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:320:in `load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:196:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

**Comment by taorepoara** [comment]
> Should be fix by [gouz/homebrew-tools#2](https://github.com/gouz/homebrew-tools/pull/2)

It's better but not fixed. The `slidesk` file is not found.
I don't now how deb packages work (yet)...
It might have a suffix or something (ex: `slidesk-linux`) ?

Here are the logs:

```bash
brew install slidesk
==> Fetching gouz/tools/slidesk
==> Downloading https://github.com/slidesk/slidesk/releases/download/2.10.1/slidesk_2.10.1_amd64.deb
Already downloaded: /home/taorepoara/.cache/Homebrew/downloads/2c25528de555d255a4f634c9e62d42e366cbac2724f86eeede4b31e74a2a344e--slidesk_2.10.1_amd64.deb
==> Installing slidesk from gouz/tools
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - slidesk
```

I got an equivalent issue with Dofigen since the filename is different for each target.

Here is my rb file (might help): https://github.com/lenra-io/homebrew-tools/blob/main/dofigen.rb

**Comment by yodamad** [comment]
@taorepoara thank for the pointer, I'll have a look. Maybe we have to change the binary create by slidesk
I'll try to have a look tonight

**Comment by yodamad** [comment]
Should be fix with 2 PR (the one in `slidesk` & the one in `gouz/homebrew-tools`)

**Comment by taorepoara** [comment]
> Should be fix with 2 PR (the one in `slidesk` & the one in `gouz/homebrew-tools`)

I'll try it later

**Comment by taorepoara** [comment]
Hi,

I still have the problem:

```bash
$ brew install slidesk
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
==> Updated Homebrew from 4.4.16 (55475cb11a) to 4.4.19 (9b6de82d2d).
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
acme.sh                 babelfish               chiko                   diary                   precious                redocly-cli             sdl3                    ubi


The 4.4.19 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/4.4.19
==> Fetching gouz/tools/slidesk
==> Downloading https://github.com/slidesk/slidesk/releases/download/2.10.1/slidesk_2.10.1_amd64.deb
Already downloaded: /home/taorepoara/.cache/Homebrew/downloads/2c25528de555d255a4f634c9e62d42e366cbac2724f86eeede4b31e74a2a344e--slidesk_2.10.1_amd64.deb
==> Installing slidesk from gouz/tools
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - slidesk
```

**Comment by taorepoara** [comment]
Here is the list of elements to change in the `slidesk.rb` formula:

- Remove the final `on_linux` block: https://github.com/gouz/homebrew-tools/blob/eae4e271a6319dc1d8b06f329c5915b138121d15/slidesk.rb#L39
- Fix the base URL value: `https://github.com/slidesk/slidesk/releases/download/#{version}`
- Change the `@@file_name` values since for now they look like `release_...` but after the PR #177 they will look like`slidesk_...`. One other way would be to do not change the release files names for now.
- Merge this PR: #177 


For now, here is a working version of the `slidesk.rb` file (not working on ARM because of the SHA256 value):

```ruby
class Slidesk < Formula
    desc "Speaker companion"
    homepage "https://github.com/gouz/homebrew-tools"

    version "2.10.1"
    BASE_URL = "https://github.com/slidesk/slidesk/releases/download/#{version}"

    MAC_ARM_SHA = "4e105209211f6dc6f2d5325f5a872aa751b1e9a7b24851b584be35b02b8705ce"
    MAC_AMD_SHA = "738efe5ab5753d56b35b0562fb4c0a807f7bda3dde0e72a5ec3911d12944356d"
    LINUX_ARM_SHA = "4e105209211f6dc6f2d5325f5a872aa751b1e9a7b24851b584be35b02b8705ce"
    LINUX_AMD_SHA = "bbd1f8948a605d185255f80fc3033935480aacf32b8bb1cada7573dc08589032"

    on_macos do
        on_arm do
            @@file_name = "release_mac"
            sha256 MAC_ARM_SHA
        end
        on_intel do
            @@file_name = "release_mac_intel"
            sha256 MAC_AMD_SHA
        end
    end
    on_linux do
        on_arm do
            @@file_name = "release_linux_arm"
            sha256 LINUX_ARM_SHA
        end
        on_intel do
            @@file_name = "release_ubuntu"
            sha256 LINUX_AMD_SHA
        end
    end

    url "#{BASE_URL}/#{@@file_name}.tar.gz"

    def install
        bin.install "slidesk" => "slidesk"
    end
end
```

**Comment by yodamad** [comment]
@taorepoara thank you for help
I've reopen a PR to fix my mistakes on `slidesk.rb`

I'll keep `slidesk` rather than `release` because in all cases, the workflow PR has to be merged before for homebrew-tools to be updated correctly, so this PR includes the renaming of the binaries

**Comment by yodamad** [comment]
Hum very strange, locally I've got the correct `rb`file 
Maybe the merge didn't worked correctly
Repush it

**Comment by yodamad** [comment]
https://github.com/gouz/homebrew-tools/pull/4/conflicts : it does nothing correctly :( 

@gouz : to resolve conflict, edit file and replace everything because merge proposition is completely wrong

**Comment by gouz** [comment]
@taorepoara new version must fix your issue

**Comment by taorepoara** [comment]
Indeed ! 

```bash
taorepoara@lenra-taorepoara:~$ brew install slidesk
==> Downloading https://formulae.brew.sh/api/formula.jws.json
==> Fetching gouz/tools/slidesk
==> Downloading https://github.com/slidesk/slidesk/releases/download/2.11.1/slid
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Installing slidesk from gouz/tools
==> Downloading https://formulae.brew.sh/api/cask.jws.json
🍺  /home/linuxbrew/.linuxbrew/Cellar/slidesk/2.11.1: 4 files, 95.2MB, built in 1 second
==> Running `brew cleanup slidesk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /home/taorepoara/.cache/Homebrew/slidesk--2.10.1.deb... (35MB)
Removing: /home/taorepoara/.cache/Homebrew/slidesk--2.10.1.tar.gz... (36MB)
taorepoara@lenra-taorepoara:~$ slidesk --version
 ____(•)-
(SliDesk) v:2.11.1

2.11.1
```

**Comment by gouz** [comment]
thanks for your help
